spring:
  profiles:
    active: local # 기본 환경 선택
    thymeleaf :
      prefix : classpath:templates/
      check-template-location : true
      suffix : .html

# local
---
spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://localhost:3306/sellerhelper?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
# prod
---